### PR TITLE
Remove display: block from template

### PR DESCRIPTION
**Pull request by markoscc**
# What does this PR Do?
Remove the `display: block` without modifying the `ui-bootstrap-tpls.js`

**Priority 1 as is happening live**

More info on https://github.com/Olapic/LemuramaAdmin/pull/313

# How it should be manually tested?
Go here and follow instructions: https://github.com/Olapic/LemuramaAdmin/pull/313

# What are the relevant tickets?
https://photorank.atlassian.net/browse/IQA-6035

# There are related PRs?
https://github.com/Olapic/Snow/pull/235
https://github.com/Olapic/LemuramaAdmin/pull/313

# Who must review?
@ezequielgarcia88 
@charly22

### CODE REVIEW

**Comment by charly22** [comment]
:shipit:

**Comment by maxigimenez** [comment]
LGTM 👍

**Comment by charly22** [comment]
@maxigimenez your shipits worth just by a half, desertor! :P

**Comment by xeBuz** [comment]
My two cents, another desertor-half-shipit :+1: 
lgtm shipit

**Comment by ezequielgarcia88** [comment]
🐑

**Pull request merged**
