### PR TITLE
Codestyle fixes

### PR DESCRIPTION
**Pull request by charly22**
# What does this PR do?

I've replaced tab for spaces, so I'm recommending code review with [`w=1`](https://github.com/Olapic/angular-popup-boxes/pull/1/files?w=1) hack

Also I've made some changed due jshint suggestions

# How to test this manually?

I haven't added any substantial modification, so, the behaviour should be unaltered

### CODE REVIEW

**Comment by dottavio** [comment]
@charly22 can you add [.editorconfig](https://github.com/Olapic/SDK-JS/blob/master/.editorconfig) ?

**Comment by charly22** [comment]
@dottavio Yes, I did it in here https://github.com/Olapic/angular-popup-boxes/pull/2

**Comment by dottavio** [comment]
:ship:

**Comment by loverajoel** [comment]
:shipit:

**Pull request merged**
