### PR TITLE
Angular 1.5

### PR DESCRIPTION
**Pull request by charly22**
# What does this PR do?
Migrates from Angular 1.3 to 1.5.

# How to test this manually?
On the implementation: https://github.com/Olapic/LemuramaAdmin/pull/235

# Jira
https://photorank.atlassian.net/browse/TD-664

### CODE REVIEW

**Comment by maxigimenez** [comment]
:shipit: 👍

**Comment by charly22** [comment]
LOL

**Comment by mdottavio** [comment]
LGTM! 🚢

**Comment by sergiolepore** [comment]
:shipit: !

**Comment by emiprandi** [comment]
:shipit:

**Pull request merged**
