### PR TITLE
Add custom class support via options

### PR DESCRIPTION
**Pull request by sergiolepore**
# What does this PR Do?

Adds custom class support via options. Why? For [PBL-1632](https://photorank.atlassian.net/browse/PBL-1632) I need to change the top margin of the modal. Since the modal appends directly to the body and has its own generic class, I can't change any property of it without breaking it in another place.

# How it should be manually tested?

(I'll paste a link to PBL-1632's PR)

# What are the relevant tickets?

https://photorank.atlassian.net/browse/PBL-1632

# Who must review?

@charly22

### CODE REVIEW

**Comment by ezequielgarcia88** [comment]
LGTM :shipit:

**Comment by mdottavio** [comment]
LGTM 🚢

**Comment by charly22** [comment]
According to what we talked off line, we don't need this anymore since we modified the margin to "center" the modal for all sections at the same.

**Comment by sergiolepore** [comment]
Thank you guys. Closing this.

**Pull request closed without merging**
